import type { HrStore } from "@/lib/store/types";

export function createInitialStore(): HrStore {
  return {
    employees: [
      {
        id: "emp-amelia",
        name: "Amelia Chen",
        email: "amelia.hr@kastros.demo",
        title: "Chief People Officer",
        location: "Singapore",
        status: "Active",
        reportsToEmail: null,
      },
      {
        id: "emp-marcus",
        name: "Marcus Okonkwo",
        email: "marcus.manager@kastros.demo",
        title: "Logistics Lead",
        location: "Rotterdam",
        status: "Active",
        reportsToEmail: "amelia.hr@kastros.demo",
      },
      {
        id: "emp-elena",
        name: "Elena Rossi",
        email: "elena.employee@kastros.demo",
        title: "QA & Certifications",
        location: "Milan",
        status: "Active",
        reportsToEmail: "marcus.manager@kastros.demo",
      },
      {
        id: "emp-jonas",
        name: "Jonas Berg",
        email: "jonas.payroll@kastros.demo",
        title: "Payroll & Compliance",
        location: "Stockholm",
        status: "Active",
        reportsToEmail: "amelia.hr@kastros.demo",
      },
      {
        id: "emp-priya",
        name: "Priya Nair",
        email: "priya.recruiter@kastros.demo",
        title: "Talent Partner",
        location: "Dubai",
        status: "Active",
        reportsToEmail: "amelia.hr@kastros.demo",
      },
      {
        id: "emp-noah",
        name: "Noah Sato",
        email: "security.admin@kastros.demo",
        title: "Security Operations",
        location: "Tokyo",
        status: "Active",
        reportsToEmail: "amelia.hr@kastros.demo",
      },
    ],
    leaveRequests: [
      {
        id: "lv-1",
        requesterEmail: "elena.employee@kastros.demo",
        kind: "Annual leave",
        start: "2026-05-12",
        end: "2026-05-16",
        status: "Pending",
        decidedByEmail: null,
        note: "Visiting certification lab partner.",
      },
      {
        id: "lv-2",
        requesterEmail: "marcus.manager@kastros.demo",
        kind: "Wellness day",
        start: "2026-04-22",
        end: "2026-04-22",
        status: "Approved",
        decidedByEmail: "amelia.hr@kastros.demo",
        note: null,
      },
    ],
    jobs: [
      {
        id: "job-1",
        title: "Commodity Risk Analyst",
        location: "Hybrid · London",
        stage: "Phone screen",
        applicantCount: 12,
      },
      {
        id: "job-2",
        title: "Origin Quality Lead",
        location: "Field · LATAM",
        stage: "Offer",
        applicantCount: 3,
      },
      {
        id: "job-3",
        title: "Trade Finance Associate",
        location: "Remote · EU",
        stage: "Applied",
        applicantCount: 28,
      },
    ],
    training: [
      {
        id: "tr-1",
        assigneeEmail: "elena.employee@kastros.demo",
        name: "Trade compliance refresh",
        due: "Due in 12 days",
        status: "Required",
      },
      {
        id: "tr-2",
        assigneeEmail: "elena.employee@kastros.demo",
        name: "Food safety & contamination response",
        due: "Completed",
        status: "Done",
      },
      {
        id: "tr-3",
        assigneeEmail: "marcus.manager@kastros.demo",
        name: "Anti-bribery & third parties",
        due: "Due in 45 days",
        status: "Required",
      },
    ],
    documents: [
      {
        id: "doc-1",
        name: "Master services agreement · template",
        owner: "Legal",
        sensitivity: "Confidential",
        createdByEmail: "amelia.hr@kastros.demo",
      },
      {
        id: "doc-2",
        name: "Quality certificate · batch 26-Q2-118",
        owner: "QA",
        sensitivity: "Internal",
        createdByEmail: "elena.employee@kastros.demo",
      },
    ],
    cases: [
      {
        id: "case-1",
        reference: "CASE-1042",
        topic: "Workplace accommodation",
        status: "Under review",
        opened: "2026-04-18",
        openedByEmail: "amelia.hr@kastros.demo",
      },
      {
        id: "case-2",
        reference: "CASE-1038",
        topic: "Travel policy exception",
        status: "Resolved",
        opened: "2026-03-02",
        openedByEmail: "marcus.manager@kastros.demo",
      },
    ],
    goals: [
      {
        id: "g-1",
        ownerEmail: "elena.employee@kastros.demo",
        title: "Reduce lab turnaround time by 10%",
        progressPct: 45,
        cycle: "H1 2026",
      },
      {
        id: "g-2",
        ownerEmail: "marcus.manager@kastros.demo",
        title: "On-time shipment rate ≥ 98%",
        progressPct: 72,
        cycle: "H1 2026",
      },
    ],
    payroll: {
      month: "April 2026",
      employeesPaid: 236,
      exceptions: 0,
      note: "Retro bonus accruals booked per finance memo 2026-04-12.",
    },
    audit: [
      {
        at: "2026-05-04T09:12:00.000Z",
        actor: "priya.recruiter@kastros.demo",
        action: "Exported recruiting pipeline summary",
        ip: "10.12.4.22",
      },
      {
        at: "2026-05-03T16:40:00.000Z",
        actor: "system",
        action: "Scheduled key rotation reminder",
        ip: "—",
      },
    ],
  };
}
