import type { HrStore } from "@/lib/store/types";

function probationDate(joiningDate: string, months: number): string {
  const dt = new Date(joiningDate);
  dt.setMonth(dt.getMonth() + months);
  return dt.toISOString().slice(0, 10);
}

export function createInitialStore(): HrStore {
  return {
    employees: [
      {
        id: "emp-ceo",
        name: "Hassan Malik",
        fatherName: "Abdul Malik",
        email: "ceo@kastros.demo",
        title: "Chief Executive Officer",
        location: "Dubai",
        status: "Active",
        department: "Executive",
        employmentType: "Permanent",
        joiningDate: "2024-01-05",
        probationMonths: 3,
        probationCompletionDate: probationDate("2024-01-05", 3),
        companyPhone: "+971-4-000-1000",
        personalPhone: "+971-50-000-1000",
        emergencyContacts: [{ name: "Sara Malik", relation: "Spouse", phone: "+971-50-000-1001" }],
        familyRelations: [{ name: "Sara Malik", relation: "Spouse", firmOrEmployer: "N/A", linkedToTraderOrMerchandiser: false }],
        reportsToEmail: null,
      },
      {
        id: "emp-amelia",
        name: "Amelia Chen",
        fatherName: "Min Chen",
        email: "amelia.hr@kastros.demo",
        title: "Chief People Officer",
        location: "Singapore",
        status: "Active",
        department: "HR",
        employmentType: "Permanent",
        joiningDate: "2025-01-10",
        probationMonths: 3,
        probationCompletionDate: probationDate("2025-01-10", 3),
        companyPhone: "+65-6000-2000",
        personalPhone: "+65-9000-2000",
        emergencyContacts: [{ name: "Ian Chen", relation: "Brother", phone: "+65-9000-2001" }],
        familyRelations: [{ name: "Ian Chen", relation: "Brother", firmOrEmployer: "N/A", linkedToTraderOrMerchandiser: false }],
        reportsToEmail: "ceo@kastros.demo",
      },
      {
        id: "emp-marcus",
        name: "Marcus Okonkwo",
        fatherName: "Emeka Okonkwo",
        email: "marcus.manager@kastros.demo",
        title: "Logistics Lead",
        location: "Rotterdam",
        status: "Active",
        department: "Operations",
        employmentType: "Permanent",
        joiningDate: "2025-02-01",
        probationMonths: 3,
        probationCompletionDate: probationDate("2025-02-01", 3),
        companyPhone: "+31-10-555-9000",
        personalPhone: "+31-6-555-9000",
        emergencyContacts: [{ name: "Ada Okonkwo", relation: "Spouse", phone: "+31-6-555-9001" }],
        familyRelations: [{ name: "Ada Okonkwo", relation: "Spouse", firmOrEmployer: "N/A", linkedToTraderOrMerchandiser: false }],
        reportsToEmail: "ceo@kastros.demo",
      },
      {
        id: "emp-elena",
        name: "Elena Rossi",
        fatherName: "Marco Rossi",
        email: "elena.employee@kastros.demo",
        title: "QA & Certifications",
        location: "Milan",
        status: "Active",
        department: "Quality",
        employmentType: "Contractual",
        joiningDate: "2026-02-08",
        probationMonths: 3,
        probationCompletionDate: probationDate("2026-02-08", 3),
        companyPhone: "+39-02-1111-9000",
        personalPhone: "+39-333-111-9000",
        emergencyContacts: [{ name: "Laura Rossi", relation: "Mother", phone: "+39-333-111-9001" }],
        familyRelations: [{ name: "Gianni Rossi", relation: "Uncle", firmOrEmployer: "Rossi Grains", linkedToTraderOrMerchandiser: true }],
        reportsToEmail: "marcus.manager@kastros.demo",
      },
      {
        id: "emp-jonas",
        name: "Jonas Berg",
        fatherName: "Lars Berg",
        email: "jonas.payroll@kastros.demo",
        title: "Payroll & Compliance",
        location: "Stockholm",
        status: "Active",
        department: "Finance",
        employmentType: "Permanent",
        joiningDate: "2025-05-17",
        probationMonths: 3,
        probationCompletionDate: probationDate("2025-05-17", 3),
        companyPhone: "+46-8-700-9000",
        personalPhone: "+46-70-700-9000",
        emergencyContacts: [{ name: "Mia Berg", relation: "Spouse", phone: "+46-70-700-9001" }],
        familyRelations: [{ name: "Mia Berg", relation: "Spouse", firmOrEmployer: "N/A", linkedToTraderOrMerchandiser: false }],
        reportsToEmail: "amelia.hr@kastros.demo",
      },
      {
        id: "emp-priya",
        name: "Priya Nair",
        fatherName: "Ravi Nair",
        email: "priya.recruiter@kastros.demo",
        title: "Talent Partner",
        location: "Dubai",
        status: "Active",
        department: "HR",
        employmentType: "Permanent",
        joiningDate: "2025-03-12",
        probationMonths: 3,
        probationCompletionDate: probationDate("2025-03-12", 3),
        companyPhone: "+971-4-700-9000",
        personalPhone: "+971-50-700-9000",
        emergencyContacts: [{ name: "Anjali Nair", relation: "Sister", phone: "+971-50-700-9001" }],
        familyRelations: [{ name: "Anjali Nair", relation: "Sister", firmOrEmployer: "N/A", linkedToTraderOrMerchandiser: false }],
        reportsToEmail: "amelia.hr@kastros.demo",
      },
      {
        id: "emp-noah",
        name: "Noah Sato",
        fatherName: "Kenji Sato",
        email: "security.admin@kastros.demo",
        title: "Security Operations",
        location: "Tokyo",
        status: "Active",
        department: "Security",
        employmentType: "Permanent",
        joiningDate: "2025-06-01",
        probationMonths: 3,
        probationCompletionDate: probationDate("2025-06-01", 3),
        companyPhone: "+81-3-1111-3000",
        personalPhone: "+81-80-1111-3000",
        emergencyContacts: [{ name: "Yui Sato", relation: "Spouse", phone: "+81-80-1111-3001" }],
        familyRelations: [{ name: "Yui Sato", relation: "Spouse", firmOrEmployer: "N/A", linkedToTraderOrMerchandiser: false }],
        reportsToEmail: "ceo@kastros.demo",
      },
    ],
    leaveRequests: [
      {
        id: "lv-1",
        requesterEmail: "elena.employee@kastros.demo",
        kind: "Annual leave",
        start: "2026-05-12",
        end: "2026-05-16",
        status: "PendingHR",
        decidedByEmail: null,
        hrDecisionByEmail: null,
        ceoDecisionByEmail: null,
        note: "Visiting certification lab partner.",
      },
      {
        id: "lv-2",
        requesterEmail: "marcus.manager@kastros.demo",
        kind: "Annual leave",
        start: "2026-04-22",
        end: "2026-04-23",
        status: "PendingCEO",
        decidedByEmail: "amelia.hr@kastros.demo",
        hrDecisionByEmail: "amelia.hr@kastros.demo",
        ceoDecisionByEmail: null,
        note: null,
      },
    ],
    jobs: [
      {
        id: "job-1",
        title: "Commodity Risk Analyst",
        location: "Hybrid · London",
        stage: "Phone screen",
        applicantCount: 2,
        description:
          "Support hedging and exposure reporting for softs and grains. Strong Excel + risk systems; commodity markets experience preferred.",
      },
      {
        id: "job-2",
        title: "Origin Quality Lead",
        location: "Field · LATAM",
        stage: "Offer",
        applicantCount: 1,
        description: "Lead field inspections and supplier quality programs across origin partners. Fluency in Spanish or Portuguese is a plus.",
      },
      {
        id: "job-3",
        title: "Trade Finance Associate",
        location: "Remote · EU",
        stage: "Applied",
        applicantCount: 2,
        description: "Letters of credit, documentary collections, and counterparty limits for trade flows. Prior banking or commodity trade finance a plus.",
      },
    ],
    jobApplications: [
      {
        id: "ja-1",
        jobId: "job-1",
        fullName: "Alex Morgan",
        email: "alex.morgan@example.com",
        phone: "+44 7700 900123",
        linkedIn: "https://www.linkedin.com/in/example-am",
        currentCompany: "Riverside Commodities",
        yearsExperience: "5 years",
        salaryExpectation: "£65–70k",
        noticePeriod: "1 month",
        coverLetter: "Interested in hybrid risk analytics role; hedging background in softs.",
        cvStoredRef: null,
        cvOriginalName: null,
        submittedAt: "2026-05-01T14:22:00.000Z",
      },
      {
        id: "ja-2",
        jobId: "job-1",
        fullName: "Samira Khan",
        email: "samira.k@example.com",
        phone: "+44 7700 900456",
        linkedIn: null,
        currentCompany: "Freelance analyst",
        yearsExperience: "3 years",
        salaryExpectation: null,
        noticePeriod: "2 weeks",
        coverLetter: null,
        cvStoredRef: null,
        cvOriginalName: null,
        submittedAt: "2026-05-02T09:05:00.000Z",
      },
      {
        id: "ja-3",
        jobId: "job-2",
        fullName: "Diego Alvarez",
        email: "diego.alvarez@example.com",
        phone: "+52 55 1234 5678",
        linkedIn: "https://www.linkedin.com/in/example-da",
        currentCompany: "AgroNova",
        yearsExperience: "8 years",
        salaryExpectation: null,
        noticePeriod: "1 month",
        coverLetter: "Field quality lead for five years in coffee and cocoa.",
        cvStoredRef: null,
        cvOriginalName: null,
        submittedAt: "2026-04-28T11:40:00.000Z",
      },
      {
        id: "ja-4",
        jobId: "job-3",
        fullName: "Ingrid Larsen",
        email: "ingrid.larsen@example.com",
        phone: "+47 412 55 990",
        linkedIn: null,
        currentCompany: "Nordic Trade Bank",
        yearsExperience: "4 years",
        salaryExpectation: "€58k",
        noticePeriod: "3 months",
        coverLetter: null,
        cvStoredRef: null,
        cvOriginalName: null,
        submittedAt: "2026-05-05T08:15:00.000Z",
      },
      {
        id: "ja-5",
        jobId: "job-3",
        fullName: "Paul Mensah",
        email: "paul.mensah@example.com",
        phone: "+31 6 1234 8899",
        linkedIn: null,
        currentCompany: "Rotterdam FinCo",
        yearsExperience: "6 years",
        salaryExpectation: null,
        noticePeriod: "1 month",
        coverLetter: "LC and documentary credit specialist.",
        cvStoredRef: null,
        cvOriginalName: null,
        submittedAt: "2026-05-04T16:00:00.000Z",
      },
    ],
    training: [
      {
        id: "tr-1",
        assigneeEmail: "elena.employee@kastros.demo",
        name: "Trade compliance refresh",
        provider: "Internal",
        providerName: "Kastros HR",
        trainingMaterialPptx: "trade-compliance-q2.pptx",
        attendanceMarked: true,
        due: "2026-05-25",
        status: "Required",
      },
      {
        id: "tr-2",
        assigneeEmail: "elena.employee@kastros.demo",
        name: "Advanced commodity hedging",
        provider: "External",
        providerName: "Coursera",
        trainingMaterialPptx: null,
        attendanceMarked: false,
        due: "2026-06-20",
        status: "Done",
      },
    ],
    academics: [
      {
        id: "ac-1",
        employeeEmail: "elena.employee@kastros.demo",
        type: "Degree",
        title: "BSc Food Science",
        institute: "University of Milan",
        year: "2021",
        attachmentName: "elena-degree.pdf",
        storedRef: null,
      },
      {
        id: "ac-2",
        employeeEmail: "elena.employee@kastros.demo",
        type: "Certification",
        title: "ISO 22000 Internal Auditor",
        institute: "SGS",
        year: "2024",
        attachmentName: "elena-iso22000.pdf",
        storedRef: null,
      },
    ],
    documents: [
      {
        id: "doc-1",
        name: "Master services agreement · template",
        owner: "Legal",
        sensitivity: "Confidential",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: null,
        storedRef: null,
      },
      {
        id: "doc-2",
        name: "Elena Rossi · CV (recruiting dossier)",
        owner: "HR",
        sensitivity: "Internal",
        createdByEmail: "priya.recruiter@kastros.demo",
        employeeEmail: "elena.employee@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-3",
        name: "Signed employment contract",
        owner: "HR",
        sensitivity: "Confidential",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "elena.employee@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-4",
        name: "Government ID copy & work authorization",
        owner: "People Ops",
        sensitivity: "Restricted",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "elena.employee@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-5",
        name: "Bank details & tax forms (onboarding pack)",
        owner: "Payroll",
        sensitivity: "Restricted",
        createdByEmail: "jonas.payroll@kastros.demo",
        employeeEmail: "elena.employee@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-6",
        name: "Pre-employment medical clearance",
        owner: "Occupational health",
        sensitivity: "Confidential",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "elena.employee@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-7",
        name: "Hassan Malik · CEO appointment & contract",
        owner: "Board / Legal",
        sensitivity: "Confidential",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "ceo@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-8",
        name: "Marcus Okonkwo · ID & right-to-work",
        owner: "People Ops",
        sensitivity: "Restricted",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "marcus.manager@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-9",
        name: "Marcus Okonkwo · signed contract & code acknowledgement",
        owner: "HR",
        sensitivity: "Internal",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "marcus.manager@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-10",
        name: "Amelia Chen · CPO onboarding file (contract, references)",
        owner: "HR",
        sensitivity: "Confidential",
        createdByEmail: "ceo@kastros.demo",
        employeeEmail: "amelia.hr@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-11",
        name: "Jonas Berg · payroll specialist · onboarding documents",
        owner: "HR",
        sensitivity: "Internal",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "jonas.payroll@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-12",
        name: "Priya Nair · recruiter · ID & confidentiality undertaking",
        owner: "HR",
        sensitivity: "Internal",
        createdByEmail: "amelia.hr@kastros.demo",
        employeeEmail: "priya.recruiter@kastros.demo",
        storedRef: null,
      },
      {
        id: "doc-13",
        name: "Noah Sato · security clearance & NDA",
        owner: "Security",
        sensitivity: "Restricted",
        createdByEmail: "security.admin@kastros.demo",
        employeeEmail: "security.admin@kastros.demo",
        storedRef: null,
      },
    ],
    policies: [
      { id: "pol-1", title: "HR Manual", version: "v2026.1", printableUrl: "/policies/hr-manual-v2026.1.pdf" },
      { id: "pol-2", title: "Code of Conduct", version: "v2026.2", printableUrl: "/policies/code-of-conduct-v2026.2.pdf" },
    ],
    policyAcknowledgements: [
      { id: "ack-1", policyId: "pol-1", employeeEmail: "marcus.manager@kastros.demo", acknowledgedAt: "2026-04-02T09:00:00.000Z" },
      { id: "ack-2", policyId: "pol-2", employeeEmail: "marcus.manager@kastros.demo", acknowledgedAt: "2026-04-03T10:15:00.000Z" },
      { id: "ack-3", policyId: "pol-1", employeeEmail: "elena.employee@kastros.demo", acknowledgedAt: "2026-02-09T11:00:00.000Z" },
      { id: "ack-4", policyId: "pol-2", employeeEmail: "elena.employee@kastros.demo", acknowledgedAt: "2026-02-09T11:05:00.000Z" },
      { id: "ack-5", policyId: "pol-1", employeeEmail: "amelia.hr@kastros.demo", acknowledgedAt: "2025-01-11T09:00:00.000Z" },
    ],
    cases: [
      {
        id: "case-1",
        reference: "CASE-1042",
        topic: "Potential family-linked trader relationship disclosure",
        status: "Under review",
        opened: "2026-04-18",
        openedByEmail: "amelia.hr@kastros.demo",
        type: "Conflict of Interest",
        restrictedTo: ["hr_admin", "ceo"],
      },
    ],
    goals: [
      { id: "g-1", ownerEmail: "elena.employee@kastros.demo", title: "Reduce lab turnaround time by 10%", progressPct: 45, cycle: "H1 2026" },
      { id: "g-2", ownerEmail: "marcus.manager@kastros.demo", title: "On-time shipment rate >= 98%", progressPct: 72, cycle: "H1 2026" },
    ],
    reviews: [
      {
        id: "rev-1",
        employeeEmail: "elena.employee@kastros.demo",
        managerEmail: "marcus.manager@kastros.demo",
        department: "Quality",
        criteriaType: "Technical",
        grade: "B",
        comments: "Strong quality ownership; improve escalation speed.",
        cycle: "H1 2026",
      },
    ],
    payroll: {
      month: "April 2026",
      employeesPaid: 236,
      exceptions: 0,
      note: "Payroll computed from hours x rate plus allowances where applicable.",
    },
    payrollEntries: [
      {
        id: "pay-1",
        employeeEmail: "elena.employee@kastros.demo",
        month: "April 2026",
        baseSalary: 2200,
        allowances: [
          { type: "Transport", amount: 180 },
          { type: "SIM/Mobile", amount: 45 },
        ],
        hoursWorked: 168,
        hourlyRate: 12.75,
        grossPay: 2367,
      },
    ],
    audit: [
      { at: "2026-05-04T09:12:00.000Z", actor: "priya.recruiter@kastros.demo", action: "Uploaded CV metadata for Elena", ip: "10.12.4.22" },
      { at: "2026-05-03T16:40:00.000Z", actor: "system", action: "Scheduled probation reminder check", ip: "—" },
    ],
  };
}
